# Generated by Django 2.1.7 on 2019-07-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=16, unique=True)),
                ('email', models.EmailField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('head', models.ImageField(default='decault.png', upload_to='')),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('sex', models.CharField(blank=True, max_length=2, null=True)),
                ('isactivate', models.BooleanField(default=False)),
            ],
        ),
    ]
